services:
  - type: web
    name: grabby-ytdlp
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SHARED_SECRET
        generateValue: true
